// Builds and starts the full WalletFacade (shielded + unshielded + Dust)
// from the seed generated by wallet/generate-wallet.mjs, targeting the
// preview network. This is the same shielded/unshielded/Dust triple the
// official Midnight tooling builds -- see wallet-sdk-facade's WalletFacade.
//
// Known risk (see project memory "blockfrost-wallet-relay-crash"): the
// relayURL used for the submission service (Blockfrost's Node RPC WS for
// preprod) has previously been slow enough (~35-40s vs ~4s for Midnight's
// own public node) to tip the wallet SDK into timeout/retry/OOM under
// concurrent shielded+unshielded+Dust sync load. No equivalent fast public
// node is confirmed for the *preview* network specifically, so this is
// using Blockfrost's own preview Node RPC (the officially documented path)
// and may need the same fix (pointing MIDNIGHT_RPC at a faster preview
// node) if it proves too slow here too.

import * as ledger from '@midnight-ntwrk/ledger-v8';
import { HDWallet, Roles } from '@midnight-ntwrk/wallet-sdk-hd';
import { mnemonicToSeedSync } from '@scure/bip39';
import { UnshieldedWallet, createKeystore, PublicKey } from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import { ShieldedWallet } from '@midnight-ntwrk/wallet-sdk-shielded';
import { DustWallet } from '@midnight-ntwrk/wallet-sdk-dust-wallet';
import { WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { NoOpTransactionHistoryStorage } from '@midnight-ntwrk/wallet-sdk-abstractions';
import * as cfg from './config.mjs';

function deriveRoleKey(hdWallet, role) {
  const roleKey = hdWallet.selectAccount(0).selectRole(role);
  const derived = roleKey.deriveKeyAt(0);
  if (derived.type !== 'keyDerived') {
    throw new Error(`Failed to derive key for role ${role} at index 0`);
  }
  return derived.key;
}

let started;

export async function getWallet() {
  if (started) return started;

  const { mnemonic } = cfg.loadWalletSecret();
  const seed = mnemonicToSeedSync(mnemonic);
  const hdResult = HDWallet.fromSeed(seed);
  if (hdResult.type !== 'seedOk') {
    throw new Error(`Failed to derive HD wallet from seed: ${JSON.stringify(hdResult.error)}`);
  }
  const hdWallet = hdResult.hdWallet;

  const nightSecretKey = deriveRoleKey(hdWallet, Roles.NightExternal);
  const zswapSeed = deriveRoleKey(hdWallet, Roles.Zswap);
  const dustSeed = deriveRoleKey(hdWallet, Roles.Dust);
  hdWallet.clear();

  const shieldedSecretKeys = ledger.ZswapSecretKeys.fromSeed(zswapSeed);
  const dustSecretKey = ledger.DustSecretKey.fromSeed(dustSeed);
  const dustParameters = ledger.LedgerParameters.initialParameters().dust;

  const unshieldedKeystore = createKeystore(nightSecretKey, cfg.networkId);
  const unshieldedPublicKey = PublicKey.fromKeyStore(unshieldedKeystore);

  const configuration = {
    networkId: cfg.networkId,
    indexerClientConnection: {
      indexerHttpUrl: cfg.indexerHttpUrl,
      indexerWsUrl: cfg.indexerWsUrl,
    },
    txHistoryStorage: new NoOpTransactionHistoryStorage(),
    relayURL: new URL(cfg.relayUrl),
    provingServerUrl: new URL(cfg.proofServerUrl),
  };

  console.log('[wallet] connecting shielded/unshielded/Dust sub-wallets to the preview indexer…');
  const facade = await WalletFacade.init({
    configuration,
    shielded: (config) => ShieldedWallet(config).startWithSecretKeys(shieldedSecretKeys),
    unshielded: (config) => UnshieldedWallet(config).startWithPublicKey(unshieldedPublicKey),
    dust: (config) => DustWallet(config).startWithSecretKey(dustSecretKey, dustParameters),
  });

  await facade.start(shieldedSecretKeys, dustSecretKey);

  console.log('[wallet] waiting for sync (this can take a while against Blockfrost preview)…');
  await facade.waitForSyncedState();
  console.log('[wallet] synced.');

  started = { facade, shieldedSecretKeys, dustSecretKey, unshieldedKeystore };
  return started;
}

export function defaultTtl() {
  return new Date(Date.now() + 5 * 60 * 1000);
}
