// Builds and starts the full WalletFacade (shielded + unshielded + Dust)
// from the seed generated by wallet/generate-wallet.mjs, targeting the
// preview network. This is the same shielded/unshielded/Dust triple the
// official Midnight tooling builds -- see wallet-sdk-facade's WalletFacade.
//
// Known risk (see project memory "blockfrost-wallet-relay-crash"): the
// relayURL used for the submission service (Blockfrost's Node RPC WS for
// preprod) has previously been slow enough (~35-40s vs ~4s for Midnight's
// own public node) to tip the wallet SDK into timeout/retry/OOM under
// concurrent shielded+unshielded+Dust sync load. No equivalent fast public
// node is confirmed for the *preview* network specifically, so this is
// using Blockfrost's own preview Node RPC (the officially documented path)
// and may need the same fix (pointing MIDNIGHT_RPC at a faster preview
// node) if it proves too slow here too.

import * as ledger from '@midnight-ntwrk/ledger-v8';
import { HDWallet, Roles } from '@midnight-ntwrk/wallet-sdk-hd';
import { mnemonicToSeedSync } from '@scure/bip39';
import { UnshieldedWallet, createKeystore, PublicKey } from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import { ShieldedWallet } from '@midnight-ntwrk/wallet-sdk-shielded';
import { DustWallet } from '@midnight-ntwrk/wallet-sdk-dust-wallet';
import { WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { NoOpTransactionHistoryStorage } from '@midnight-ntwrk/wallet-sdk-abstractions';
import * as cfg from './config.mjs';

function deriveRoleKey(hdWallet, role) {
  const roleKey = hdWallet.selectAccount(0).selectRole(role);
  const derived = roleKey.deriveKeyAt(0);
  if (derived.type !== 'keyDerived') {
    throw new Error(`Failed to derive key for role ${role} at index 0`);
  }
  return derived.key;
}

let started;

export async function getWallet() {
  if (started) return started;

  const { mnemonic } = cfg.loadWalletSecret();
  const seed = mnemonicToSeedSync(mnemonic);
  const hdResult = HDWallet.fromSeed(seed);
  if (hdResult.type !== 'seedOk') {
    throw new Error(`Failed to derive HD wallet from seed: ${JSON.stringify(hdResult.error)}`);
  }
  const hdWallet = hdResult.hdWallet;

  const nightSecretKey = deriveRoleKey(hdWallet, Roles.NightExternal);
  const zswapSeed = deriveRoleKey(hdWallet, Roles.Zswap);
  const dustSeed = deriveRoleKey(hdWallet, Roles.Dust);
  hdWallet.clear();

  const shieldedSecretKeys = ledger.ZswapSecretKeys.fromSeed(zswapSeed);
  const dustSecretKey = ledger.DustSecretKey.fromSeed(dustSeed);
  const dustParameters = ledger.LedgerParameters.initialParameters().dust;

  const unshieldedKeystore = createKeystore(nightSecretKey, cfg.networkId);
  const unshieldedPublicKey = PublicKey.fromKeyStore(unshieldedKeystore);

  const configuration = {
    networkId: cfg.networkId,
    indexerClientConnection: {
      indexerHttpUrl: cfg.indexerHttpUrl,
      indexerWsUrl: cfg.indexerWsUrl,
      // Without this, long-lived subscriptions (needed while proving/
      // submitting, unlike the quick single-shot balance check) may sit
      // idle long enough for Blockfrost to close them; the SDK's handling
      // of that reconnect is one working theory for the Wallet.Sync loop
      // documented in project memory (private-swap-deploy-blocker).
      keepAlive: 15000,
    },
    txHistoryStorage: new NoOpTransactionHistoryStorage(),
    relayURL: new URL(cfg.relayUrl),
    provingServerUrl: new URL(cfg.proofServerUrl),
    // Required by the Dust wallet's fee calculation (TransactingCapabilityImplementation.calculateFee),
    // undocumented default. ledger-v8's own doc comment on feesWithMargin warns
    // this value is used as an *exponent* in the fee formula, so keep it small --
    // 2 gives a couple of blocks' worth of safety margin without risking a
    // blown-up fee estimate.
    costParameters: { feeBlocksMargin: 2, additionalFeeOverhead: 0n },
  };

  console.log('[wallet] connecting shielded/unshielded/Dust sub-wallets to the preview indexer…');
  const facade = await WalletFacade.init({
    configuration,
    shielded: (config) => ShieldedWallet(config).startWithSecretKeys(shieldedSecretKeys),
    unshielded: (config) => UnshieldedWallet(config).startWithPublicKey(unshieldedPublicKey),
    dust: (config) => DustWallet(config).startWithSecretKey(dustSecretKey, dustParameters),
  });

  await facade.start(shieldedSecretKeys, dustSecretKey);

  console.log('[wallet] waiting for sync (this can take a while against Blockfrost preview)…');
  // NOT facade.waitForSyncedState(): that requires an *exact* match
  // (allowedGap = 0n) between each sub-wallet's last-applied index and the
  // indexer's current position. For unshielded specifically, "applied" only
  // advances on transactions that touch this wallet -- for a low-activity
  // demo wallet, its one funding tx's sequence number will essentially
  // never exactly equal the live network's current scan position, so that
  // check can never be satisfied even though the wallet is, in every
  // practical sense, fully caught up. Confirmed empirically: with
  // diagnostic logging, all three subscriptions reach the live tip
  // (processed event id == the indexer's reported maxId) and then just
  // idle on real-time trickle -- exact-match sync simply never fires.
  // A generous gap tolerance is the correct fix, not a hack around a
  // healthy wait -- see docs/troubleshooting.md and project memory
  // (private-swap-deploy-blocker) for the full diagnosis.
  const SYNC_GAP = 1_000_000n;
  const SYNC_TIMEOUT_MS = 5 * 60 * 1000;
  await Promise.race([
    Promise.all([
      facade.shielded.waitForSyncedState(SYNC_GAP),
      facade.unshielded.waitForSyncedState(SYNC_GAP),
      facade.dust.waitForSyncedState(SYNC_GAP),
    ]),
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error(`Wallet sync did not reach isConnected within ${SYNC_TIMEOUT_MS}ms`)), SYNC_TIMEOUT_MS)
    ),
  ]);
  console.log('[wallet] synced.');

  started = { facade, shieldedSecretKeys, dustSecretKey, unshieldedKeystore };
  return started;
}

// The Node RPC client used for submission (@polkadot/api's WsProvider) is
// created once when the facade starts and kept for the process's lifetime.
// By the time a transaction is actually ready to submit -- after sync,
// building, and (for proof-requiring transactions) proving, which together
// can take minutes -- that connection has often gone stale and the specific
// in-flight submitAndWatchExtrinsic subscription fails outright rather than
// surviving reconnect. The transaction itself is already fully built at
// this point, so retrying just the submission call (not the whole
// sync+build+prove pipeline) is cheap and is the correct fix, confirmed by
// repeated failures at this exact step -- see docs/troubleshooting.md.
export async function submitWithRetry(facade, finalizedTx, attempts = 5, delayMs = 3000) {
  let lastErr;
  for (let i = 1; i <= attempts; i++) {
    try {
      return await facade.submitTransaction(finalizedTx);
    } catch (err) {
      lastErr = err;
      console.log(`[wallet] submit attempt ${i}/${attempts} failed (${err?.message ?? err}), retrying…`);
      await new Promise((resolve) => setTimeout(resolve, delayMs));
    }
  }
  throw lastErr;
}

export function defaultTtl() {
  return new Date(Date.now() + 5 * 60 * 1000);
}
