#!/usr/bin/env node
// Deploys hidden-order.compact to the Midnight preview network using the
// local proof server and the wallet generated by wallet/generate-wallet.mjs.
// Writes the resulting contract address back into .env as CONTRACT_ADDRESS.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import * as cfg from '../backend/src/midnight/config.mjs';
import { deploy } from '../backend/src/midnight/contractClient.mjs';

function writeContractAddressToEnv(address) {
  let contents = existsSync(cfg.envFile) ? readFileSync(cfg.envFile, 'utf8') : '';
  if (/^CONTRACT_ADDRESS=.*$/m.test(contents)) {
    contents = contents.replace(/^CONTRACT_ADDRESS=.*$/m, `CONTRACT_ADDRESS=${address}`);
  } else {
    contents += `${contents.endsWith('\n') || contents === '' ? '' : '\n'}CONTRACT_ADDRESS=${address}\n`;
  }
  writeFileSync(cfg.envFile, contents, 'utf8');
}

async function main() {
  if (process.env.CONTRACT_ADDRESS) {
    console.log(`CONTRACT_ADDRESS already set in .env (${process.env.CONTRACT_ADDRESS}) -- delete it first to redeploy.`);
    return;
  }

  console.log('Deploying hidden-order.compact to Midnight preview...');
  const { contractAddress, txHash } = await deploy();

  console.log('');
  console.log('Deployed.');
  console.log(`Contract address: ${contractAddress}`);
  console.log(`Deploy tx hash:   ${txHash}`);
  console.log(`Blockscout:       ${process.env.BLOCKSCOUT_URL ?? 'https://explorer.preview.midnight.network'}/tx/${txHash}`);

  writeContractAddressToEnv(contractAddress);
  console.log('');
  console.log('Wrote CONTRACT_ADDRESS to .env.');
}

main()
  .catch((err) => {
    console.error('Deploy failed:', err);
    process.exitCode = 1;
  })
  .finally(() => {
    // The wallet facade leaves its indexer/node WebSocket connections open,
    // so without an explicit exit the process hangs indefinitely after a
    // failed deploy instead of returning control (and a nonzero exit code)
    // to the caller.
    process.exit(process.exitCode ?? 0);
  });
