// Connects to the Lace (Midnight) wallet extension in-browser via the real
// @midnight-ntwrk/dapp-connector-api types, instead of a hand-rolled
// `window.midnight.mnLace` shape. Falls back to manual address entry when
// no injected wallet extension is present, since the demo needs to work
// whether or not the judge has Lace installed.
//
// Ported from the wallet-connect pattern in midnightntwrk/example-zkloan
// (zkloan-credit-scorer-ui/src/contexts/ZKLoanContext.tsx): wallets are
// injected under `window.midnight[key]` (mnLace for Lace), and
// `InitialAPI.connect(networkId)` resolves to a `ConnectedAPI` once the
// user approves the connection in the extension.
import type { InitialAPI, ConnectedAPI } from '@midnight-ntwrk/dapp-connector-api';

declare global {
  interface Window {
    midnight?: Record<string, InitialAPI>;
  }
}

const NETWORK_ID = process.env.NEXT_PUBLIC_NETWORK_ID ?? 'preview';

let connectedApi: ConnectedAPI | null = null;

export function hasInjectedWallet(): boolean {
  return typeof window !== 'undefined' && Boolean(window.midnight && Object.keys(window.midnight).length > 0);
}

function findInjectedWallet(): InitialAPI | undefined {
  if (typeof window === 'undefined' || !window.midnight) return undefined;
  return window.midnight.mnLace ?? Object.values(window.midnight)[0];
}

// Connects to Lace and returns the shielded address to display, but keeps
// the full ConnectedAPI cached module-side for lib/contract.ts to build
// browser-side providers from (see getConnectedWallet()).
export async function connectLaceWallet(): Promise<string | null> {
  const initialApi = findInjectedWallet();
  if (!initialApi) return null;

  const api = await initialApi.connect(NETWORK_ID);
  connectedApi = api;
  const addresses = await api.getShieldedAddresses();
  return addresses.shieldedAddress;
}

// There's no wallet-side "disconnect" call in the dapp-connector-api --
// per-origin authorization lives in the extension itself. Disconnecting
// here just means the dApp stops using the cached API and forgets it.
export function disconnectWallet(): void {
  connectedApi = null;
}

export function getConnectedWallet(): ConnectedAPI | null {
  return connectedApi;
}

export function isWalletConnected(): boolean {
  return connectedApi !== null;
}

// Matches the real format generated by wallet/generate-wallet.mjs and
// verified by round-tripping through the SDK's own Bech32m parser --
// mn_addr_preview1<bech32m data>. Not full Bech32m checksum validation,
// just enough to catch an obviously wrong paste (empty, wrong network,
// wrong address type) before it hits the backend.
const PREVIEW_ADDRESS_PATTERN = /^mn_addr_preview1[a-z0-9]{20,}$/;

export function isValidPreviewAddress(address: string): boolean {
  return PREVIEW_ADDRESS_PATTERN.test(address.trim());
}
