// Minimal Lace (Midnight) wallet connector. Falls back to manual address
// entry when no injected wallet extension is present, since the hackathon
// demo needs to work whether or not the judge has Lace installed.

declare global {
  interface Window {
    midnight?: {
      mnLace?: {
        isEnabled: () => Promise<boolean>;
        enable: () => Promise<{ state: () => Promise<{ address: string }> }>;
      };
    };
  }
}

export async function connectLaceWallet(): Promise<string | null> {
  if (typeof window === 'undefined' || !window.midnight?.mnLace) return null;
  const api = await window.midnight.mnLace.enable();
  const state = await api.state();
  return state.address;
}

export function hasInjectedWallet(): boolean {
  return typeof window !== 'undefined' && Boolean(window.midnight?.mnLace);
}

// Matches the real format generated by wallet/generate-wallet.mjs and
// verified by round-tripping through the SDK's own Bech32m parser --
// mn_addr_preview1<bech32m data>. Not full Bech32m checksum validation,
// just enough to catch an obviously wrong paste (empty, wrong network,
// wrong address type) before it hits the backend.
const PREVIEW_ADDRESS_PATTERN = /^mn_addr_preview1[a-z0-9]{20,}$/;

export function isValidPreviewAddress(address: string): boolean {
  return PREVIEW_ADDRESS_PATTERN.test(address.trim());
}
